rosbag_recorder:
  ros__parameters:
    recorder:
      # Output directory for ROS2 bags
      output_directory: "/home/user/rosbags"
      
      # Prefix for bag directory names
      bag_prefix: "sync_data"
      
      # Topics selection
      record_synchronized: true  # Record synchronized data (/synchronized/*)
      record_raw: false          # Record raw sensor data
      record_lidar: true         # Include LiDAR data
      record_gnss: true          # Include GNSS data
      record_metrics: true       # Include synchronization metrics
      
      # Camera names to record
      camera_names: ["ZED_CAMERA_2i", "ZED_CAMERA_X0", "ZED_CAMERA_X1"]
      
      # Bag storage options
      compression_mode: "file"   # file, message, or none
      split_size: 0              # Split size in MB, 0 for no splitting
      duration: 0                # Maximum recording duration in seconds, 0 for unlimited
      max_bag_files: 5           # Maximum number of bag files to keep, 0 for unlimited