set(_AMENT_PACKAGE_NAME "data_aquisition")
set(data_aquisition_VERSION "0.1.0")
set(data_aquisition_MAINTAINER "Maintainer <maintainer@example.com>")
set(data_aquisition_BUILD_DEPENDS "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "lifecycle_msgs" "sensor_msgs" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "diagnostic_msgs" "diagnostic_updater" "nav_msgs" "message_filters")
set(data_aquisition_BUILDTOOL_DEPENDS "ament_cmake")
set(data_aquisition_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "lifecycle_msgs" "sensor_msgs" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "diagnostic_msgs" "diagnostic_updater" "nav_msgs" "message_filters")
set(data_aquisition_BUILDTOOL_EXPORT_DEPENDS )
set(data_aquisition_EXEC_DEPENDS "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "lifecycle_msgs" "sensor_msgs" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "diagnostic_msgs" "diagnostic_updater" "nav_msgs" "message_filters")
set(data_aquisition_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(data_aquisition_GROUP_DEPENDS )
set(data_aquisition_MEMBER_OF_GROUPS )
set(data_aquisition_DEPRECATED "")
set(data_aquisition_EXPORT_TAGS)
list(APPEND data_aquisition_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
