/**:
  ros__parameters:
    # Camera settings
    camera:
      model: 'ZED_X'
      min_fps: 10.0
      max_fps: 10.0  # Fixed framerate for better synchronization
      reliable_qos: true
      qos_history_depth: 50  # Increased buffer size
      pid_p: 0.8
      pid_i: 0.2
      pid_d: 0.05
      frame_id: 'camera_link'
      
    # Image quality and resolution
    image:
      resolution: 'HD720'  # Lower resolution for better performance
      quality: 'QUALITY'   # Balance between quality and performance
      
    # Point cloud settings
    point_cloud:
      enabled: true
      resolution: 'PERFORMANCE'  # Use PERFORMANCE for better frame rate
      max_range: 15.0  # meters - reduced for better performance
      frame_id: 'camera_link'
      
    # Depth settings
    depth:
      enabled: true
      min_depth: 0.3  # meters
      max_depth: 40.0  # meters
      
    # IMU settings
    imu:
      enabled: true
      frequency: 200  # Hz
      
    # Positional tracking
    tracking:
      enabled: false  # Disable by default to save resources